input_dir: input
split_dir: split_chains
rsa_dir: rsa
interface_dir: interface
scripts:
  split_chains: scripts/split_chains.py
  naccess_chains: scripts/run_naccess_chains.py
  naccess_complex: scripts/run_naccess_complex.py
  generate_ints: scripts/generate_ints_from_asa.sh
  compute_summary: scripts/compute_summary.py
  
