name: Fortran Scripts CI

on: [push, pull_request]

jobs:
  fortran-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Fortran Compiler
        run: sudo apt-get install gfortran -y
      - name: Build and Run Fortran scripts
        run: |
          for file in $(find . -name "*.f" -o -name "*.f90" -o -name "*.f95"); do
            exe="${file%.*}.out"
            echo "Compiling $file to $exe"
            gfortran "$file" -o "$exe" && "$exe"
          done
