name: Python Scripts CI

on: [push, pull_request]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python scripts and tests
        run: |
          for file in $(find . -name "*.py"); do
            echo "Testing $file"
            python "$file"
          done
