name: Shell Script Lint and Run

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint shell scripts
        run: |
          if ls scripts/*.sh 1> /dev/null 2>&1; then
            for f in scripts/*.sh; do
              echo "Linting $f"
              shellcheck "$f"
            done
          else
            echo "No shell scripts found."
          fi

      - name: Check executability
        run: |
          if ls scripts/*.sh 1> /dev/null 2>&1; then
            chmod +x scripts/*.sh
            for f in scripts/*.sh; do
              head -n 1 "$f" | grep -qE '^#!' || echo "::warning file=$f::No shebang line found"
            done
          fi
